# Generated by Django 5.2.6 on 2025-10-10 22:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 10, 10, 22, 54, 28, 423446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('965cdc63-d6b7-4195-8ea8-c51622ac9b03'), editable=False, primary_key=True, serialize=False),
        ),
    ]
