# Generated by Django 5.2.6 on 2025-10-10 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('recipe', 'Recipe'), ('thought', 'Thought'), ('image', 'Image')])),
                ('body', models.TextField(max_length=500)),
                ('filename', models.CharField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
