# Generated by Django 5.2.6 on 2025-10-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_recipe_remove_post_user_post_steps_post_useremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/recipes/'),
        ),
    ]
